language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

notifications:
  email: false
